services:
  ayee-portal:
    image: ayee-portal:latest
    container_name: ayee-portal
    restart: always
    ports:
      - "80:4000" # Map host port 80 to container port 4000
    environment:
      - PORT=4000
      - NODE_ENV=production
